blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.storefrontui.io/v2/
    about: Find more information about the project and how to use it.
  - name: Discord Chat
    url: https://discord.vuestorefront.io/
    about: Ask questions and discuss with other Vue Storefront users in real time.
