name: Run tests
on: [push, pull_request]

jobs:
  prepare_dependencies:
    name: Prepare dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules 
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile && yarn add @vue/cli -W

  lint:
    name: Lint
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run linter and unit tests
        run: cd packages/vue && yarn lint && yarn test:unit

  cypress:
    name: e2e tests
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run Storybook 
        run: yarn storybook
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:6006"
          wait-on-timeout: 60
          command: yarn run test:e2e:headless
          config-file: packages/vue/cypress.json
          browser: chrome
          headless: true
          install: false

  build:
    name: Build
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: cd packages/vue && yarn build
